polyclinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usermanagement.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'usermanagement.views.handler404'
handler500 = 'usermanagement.views.handler500'

usermanagement/urls.py
from django.urls import path, include
from .views import *
app_name = 'usermanagement'

urlpatterns = [
    path('', index , name="index"),
    path('administrator/', administrator, name="administrator"),
    path('administrator/add-doctor', DoctorCreateView.as_view(), name="add-doctor"),
    path('administrator/list-doctors', DoctorListView.as_view(), name="list-doctors"),
    path('administrator/delete-doctor/<int:pk>/', DoctorDeleteView.as_view(), name="delete-doctor"),
    path('administrator/add-receptionist', ReceptionistCreateView.as_view(), name="add-receptionist"),
    path('administrator/list-receptionists', ReceptionistListView.as_view(), name="list-receptionists"),
    path('administrator/delete-receptionist/<int:pk>/', ReceptionistDeleteView.as_view(), name="delete-receptionist"),
    path('administrator/add-nurse', NurseCreateView.as_view(), name="add-nurse"),
    path('administrator/list-nurses', NurseListView.as_view(), name="list-nurses"),
    path('administrator/delete-nurse/<int:pk>/', NurseDeleteView.as_view(), name="delete-nurse"),
    path('administrator/list-patients', PatientListView.as_view(), name="list-patients"),
    path('administrator/delete-patient/<int:pk>/',PatientDeleteView.as_view(), name="delete-patient"),
    path('<int:pk>/user-profile/', UserUpdateView.as_view(), name="user-profile"),
    path('home/', home , name="home"),
    path('receptionist/', receptionist_home , name="receptionist_home"),
    path('receptionist/add_patient', receptionist , name="receptionist"),
    path('<role>/all_patients/', all_patients , name="all_patients"),
    path('receptionist/payment', payment, name="payment"),
    path('receptionist/paybill/<int:id>/', paybill, name="paybill"),
    path('receptionist/consultation', consultation, name="consultation"),
    path('<role>/profile/<patient_name>/', patient_profile, name="patient_profile"),
    path('nurse/', nurse_home , name="nurse_home"),
    path('nurse/takevitals', nurse , name="nurse"),
    path('doctor/', doctor , name="doctor"),
    path('consultation_queue/<consultant>/', consultation_queue, name="consultation_queue"),
    path('delete_consultation/<int:pk>/', ConsultationDeleteView.as_view(), name="consultation_delete"),
    path('add_consultation', add_consultation, name="add_consultation"),
    path('doctor_report/<int:conId>/' , doctor_report, name="doctor_report"),
    path('consultation_info/<int:conId>/', consultation_info, name='consultation_info'),
    path('modify_prescription/<int:conId>/',modify_prescription, name='modify_prescription'),
    path('search/', search , name="search"),
    path('department_info/<int:id>/', department_info, name='department_info')
]

usermanagement/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

usermanagement/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .models import *
from django.views.generic.edit import DeleteView,CreateView,UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.template import RequestContext
from django.db.models import Q

#ALL FUNCTION BASED VIEWS

#function to verify if a user has the right to access the patient profile    
def has_patient_profile_permission(request, patient_name):
        if 'Doctor' or 'Receptionist' or 'Admin' or 'Nurse' in request.user.role:
            return True
        elif (request.user.username == patient_name):
            return True
        else:
            return False
        
#return home for each role
def return_to_home_page(request, role, patient_name):
    if role == 'Doctor':
        return redirect('usermanagement:doctor')
    if role == 'Receptionist':
        return redirect('usermanagement:receptionist')
    if role == 'Nurse':
        return redirect('usermanagement:nurse')
    if role == 'Patient':
        return redirect('usermanagement:patient_profile', role=role, patient_name=patient_name)
    
#search function
def search(request):
    patients = []
    role = request.GET.get('role')
    if role == 'Patient':
        messages.info(request, "You are not allowed to search")
        return return_to_home_page(request, role, request.user.username)
    else:
        if request.method == 'POST':
            search = request.POST.get('search')
            if search is not None:
                users = CustomUser.objects.filter(Q(username__icontains=search) | Q(first_name__icontains=search) | Q(last_name__icontains=search))
                if len(users) > 0:
                    for user in users:
                        try:
                            patients.append(Patient.objects.get(user=user))
                        except ObjectDoesNotExist:
                            pass
                    if len(patients) == 0:
                            messages.info(request, "Patient with Name '"+ search + "' does not exist")
                            return return_to_home_page(request, role, 'None')
                    else:
                        context = {
                                'patients': patients,
                                'role': role
                                }
                        return render(request, 'usermanagement/'+role.lower()+'-all-patients.html',context)
                        
                else:
                    messages.info(request, "Patient with Name '"+ search + "' does not exist")
                    return return_to_home_page(request, role, 'None')
            else:
                messages.info(request, "Please enter a keyword to search")
                return return_to_home_page(request, role, 'None')
        
        messages.info(request, "Please enter a keyword to search")
        return return_to_home_page(request, role, 'None')
            

#view logic

#the index view that appears when you first launch the application
def index(request):
    return render(request, 'usermanagement/index.html')

def user_profile(request, user):
    return render(request, 'usermanagement/user-profile.html')

#the administrator page
def administrator(request):
    if request.user.is_superuser:
        request.user.active_role = 'Admin'
        request.user.save()
        total = 0
        unpaid_total = 0
        paid_total = 0
        
        for book in BillBook.objects.all():
            total = total + book.get_total()
            paid_total = paid_total + book.get_paid_total()
            unpaid_total = unpaid_total + book.get_unpaid_total()
                
        context = {
            'users': CustomUser.objects.all(), 
            'pending_consultations':Consultation.objects.filter(status = 'Pending').count(),
            'patients_registered': Patient.objects.all().count(),
            'patients_admitted': Patient.objects.filter(admitted=True).count(),
            'total_consultations':Consultation.objects.all().count(),
            'doctors': Doctor.objects.all().count(),
            'receptionists': Receptionist.objects.all().count(),
            'nurses': Nurse.objects.all().count(),
            'total_made': total,
            'paid_total': paid_total,
            'unpaid_total': unpaid_total
            }
        return render(request, 'usermanagement/admin.html', context)
    else:
        return redirect('home')

#the home view after sign in
@login_required
def home(request):
    context = {
        'departments': Department.objects.all()
    }
    return render(request, 'usermanagement/home.html', context)

def handler404(request, *args, **argv):
    response = render(request, 'usermanagement/404.html')
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render(request, 'usermanagement/500.html')
    response.status_code = 500
    return response

#the receptionist view
@login_required
def receptionist_home(request):
    request.user.active_role = 'Receptionist'
    request.user.save()
    context = {
        'pending_consultations':Consultation.objects.filter(status = 'Pending').count(),
        'patients_registered': Patient.objects.all().count(),
        'patients_admitted': Patient.objects.filter(admitted=True).count(),
    }
    return render(request, 'usermanagement/receptionist-home.html',context)


def nurse_home(request):
    request.user.active_role = 'Nurse'
    request.user.save()
    context = {
        'pending_consultations':Consultation.objects.filter(status = 'Pending').count(),
        'patients_registered': Patient.objects.all().count(),
        'patients_admitted': Patient.objects.filter(admitted=True).count(),
    }
    return render(request, 'usermanagement/nurse-home.html',context)

    
#add patient
def receptionist(request):
    request.user.active_role = 'Receptionist'
    request.user.save()
    
    #logic for post requests
    if request.method == 'POST':
        #get patient information
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        tel = request.POST.get('tel')
        date_of_birth = request.POST.get('date_of_birth')
        person_to_contact = request.POST.get('person_to_contact')
        phone_no = request.POST.get('phone_no')
        selected_user = request.POST.get('selected_user')
        gender = request.POST.get('gender')
        place_of_birth = request.POST.get('place_of_birth')
        address = request.POST.get('address')
        profession = request.POST.get('profession')
        
        #get the user object for the selected user
        try:
            user = CustomUser.objects.get(username = selected_user)
        except ObjectDoesNotExist:
            messages.info(request, "User does not exist")
            return redirect("usermanagement:receptionist")
        
        #verify if the patient is already registered
        try:
            patient = Patient.objects.get(user = user)
            messages.info(request, "This patient already exists")
            return redirect("usermanagement:receptionist")
        #if not,  create a new patient
        except ObjectDoesNotExist:
            patient = Patient.objects.create(
                user = user,
                place_of_birth = place_of_birth,
                person_to_contact = person_to_contact,
                person_to_contact_tel = phone_no,
                gender = gender,
            )
            
            #add patient to the user roles
            user.add_role('Patient')
            
            #save the user attributes that have not been saved aready
            user.add_user_info(first_name, last_name, tel, address, date_of_birth, profession)
            
            #add the registration bill to the patient bill report 
            bill_book = get_object_or_404(BillBook, patient=patient)
            Bill.objects.create(bill_book=bill_book, description="RB", amount=500)
            
            messages.info(request, "Patient has been registered")
            return redirect("usermanagement:all_patients", role = "Receptionist")
        
        
    context = {
        'all_users': [user.username for user in CustomUser.objects.all()],
        'all_patients': [patient.user.username for patient in Patient.objects.all()],
        'all_doctors': [doctor.user.username for doctor in Doctor.objects.all()]
    }
    return render(request, 'usermanagement/receptionist.html',context)


#function that handles registering consultations
def consultation(request):
    if request.method == 'POST':
        #get the selected patient and doctor from the consultation form
        selected_patient = request.POST.get('selected_patient')
        selected_doctor = request.POST.get('selected_doctor')
        patient = Patient.objects.get(user=CustomUser.objects.get(username=selected_patient))
        doctor = Doctor.objects.get(user=CustomUser.objects.get(username=selected_doctor))
        #verify if the patient has an on going consultation, before creating a new one
        try:
            consultation = Consultation.objects.filter(patient=patient).last()
            if consultation.status == "Pending":
                messages.info(request, f"{patient} has a Pending consultation appointment with {consultation.doctor.user.username}")
                return redirect("usermanagement:add_consultation")
            if consultation.status == "On Hold":
                messages.info(request, f"{patient}'s consultation appointment is still On Hold")
                return redirect("usermanagement:add_consultation")
            #if the consultation is complete, create a new consultation

usermanagement/templates/usermanagement/admin-add-doctor.html
{% extends "usermanagement/base-admin.html" %} 
{% block title %} Administrator {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
  <div class="container-fluid p-3">
    <div class="block-header">
      <h2>Add Doctor</h2>
      <small class="text-muted">Polyclinic Fultang</small>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">

        <form method="post">
          {% csrf_token %}
          {{ form|crispy}}
          <button class="btn btn-primary" type="submit"> Confirm </button>
      </form>
        
      </div>
    </div>

    </div>
  </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/admin-delete-doctor.html
{% extends "usermanagement/base-admin.html" %} 
{% block title %} Administrator {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
  <div class="container-fluid p-3">
    <div class="block-header">
      <h2>Delete Doctor</h2>
      <small class="text-muted">Polyclinic Fultang</small>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">

        <form method="post">
          {% csrf_token %}
          {{ form|crispy}}
          <button class="btn btn-primary" type="submit"> Confirm </button>
      </form>
        
      </div>
    </div>

    </div>
  </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/admin-list-nurses.html
{% extends "usermanagement/base-admin.html" %} 
{% block title %} Administrator {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
  <div class="container-fluid p-3">
    <div class="block-header">
      <h2> Nurses </h2>
      <small class="text-muted">Polyclinic Fultang</small>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">

        <div class="list-group" style="width:75%">
            {% for object in object_list%}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{object.user.first_name}} {{object.user.last_name}}
              <a href="{% url 'usermanagement:delete-nurse' object.id %}"><i class="zmdi zmdi-delete"></i></a>
              </li>
              {% empty %}
              <p> There are no Nurses Registered in the Clinic </p>
            {% endfor %}
          
        </div>  

      </div>
    </div>

    </div>
  </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/admin-list-patients.html
{% extends "usermanagement/base-admin.html" %} 
{% block title %} Administrator {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
  <div class="container-fluid p-3">
    <div class="block-header">
      <h2> Patients </h2>
      <small class="text-muted">Polyclinic Fultang</small>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">

        <div class="list-group" style="width:75%">
            {% for object in object_list%}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{object.user.first_name}} {{object.user.last_name}}
              <a href="{% url 'usermanagement:delete-patient' object.id %}"><i class="zmdi zmdi-delete"></i></a>
              </li>
              {% empty %}
              <p> There are no Patients Registered in the Clinic </p>
            {% endfor %}
          
        </div>  

      </div>
    </div>

    </div>
  </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/admin-list-receptionists.html
{% extends "usermanagement/base-admin.html" %} 
{% block title %} Administrator {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
  <div class="container-fluid p-3">
    <div class="block-header">
      <h2> Receptionists </h2>
      <small class="text-muted">Polyclinic Fultang</small>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">

        <div class="list-group" style="width:75%">
            {% for object in object_list%}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              {{object.user.first_name}} {{object.user.last_name}}
              <a href="{% url 'usermanagement:delete-receptionist' object.id %}"><i class="zmdi zmdi-delete"></i></a>
              </li>
              {% empty %}
              <p> There are no Receptionists Registered in the Clinic </p>
            {% endfor %}
          
        </div>  

      </div>
    </div>

    </div>
  </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/base-nurse.html
{% extends "usermanagement/base-executive.html" %} 
{% block title %} Nurse{% endblock %} 
{% block dashbord %}                                         
                <li><a href="{% url 'usermanagement:nurse' %}"><i class="zmdi zmdi-account-o"></i><span>Take Patient Vitals</span> </a> </li>
                <li><a href="{% url 'usermanagement:all_patients' role='Nurse' %}"><i class="zmdi zmdi-account-o"></i><span>All Patients</span> </a> </li>                                    
{% endblock %}
{% block body %}

{% endblock %}

usermanagement/templates/usermanagement/base-receptionist.html
{% extends "usermanagement/base-executive.html" %} 
{% block title %} Receptionist {% endblock %} 
{% block dashbord %}                                             
                <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-account-o"></i><span>Patients</span> </a>
                    <ul class="ml-menu">
                        <li><a href="{% url 'usermanagement:receptionist' %}">Add Patient</a></li>   
                        <li><a href="{% url 'usermanagement:all_patients' role='Receptionist' %}">All Patients</a></li>                    
                    </ul>
                </li>
                <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-calendar-check"></i><span>Consultations</span> </a>
                    <ul class="ml-menu">
                        <li><a href="{% url 'usermanagement:add_consultation' %}">Add Consultation</a></li>   
                        <li><a href="{% url 'usermanagement:consultation_queue' 'Receptionist' %}">Consultation Queue</a></li>                    
                    </ul>
                </li>
                <li><a href="{% url 'usermanagement:payment' %}"><i class="zmdi zmdi-balance-wallet"></i><span>Payment</span> </a>
                </li>
{% endblock %}
{% block body %}

{% endblock %}

usermanagement/templates/usermanagement/consultation_confirm_delete.html
{% extends "usermanagement/base-receptionist.html" %} 
{% block title %} Consultations {% endblock %} 
{% load crispy_forms_tags %}

{% block body %}
<section class="content">
    <div class="container-fluid">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            {{ form|crispy}}
            <button class="btn btn-primary" type="submit"> Confirm </button>
        </form>
    </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/consultations.html
{% extends "usermanagement/base-receptionist.html" %} 
{% block title %} Consultations {% endblock %} 

{% block body %}
<section class="content">
    <div class="container-fluid">
        {% if messages %}
        <div>
            <ul>
            {% for message in messages %}
            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            {% endfor %}
            </ul>
        </div>
         {% endif %}
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2> Consultation Queue <small>New patient consultation queue</small> </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="zmdi zmdi-more-vert"></i></a>
                                <ul class="dropdown-menu float-right">
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Another action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th> Patient Name </th>
                                    <th> Doctor Name </th>
                                    <th> Status </th>
                                    <th> Date </th>
                                    <th>  </th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for consultation in consultations %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ consultation.patient}}</td>
                                    <td>{{ consultation.doctor}}</td>
                                    <td>{{ consultation.status}}</td>
                                    <td>{{ consultation.modified}}</td>
                                    <td><a href="{% url 'usermanagement:consultation_delete' consultation.id %}"><button class="btn btn-danger"> Delete </button></a></td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

usermanagement/templates/usermanagement/doctor-patient-profile.html
{% extends "usermanagement/base-doctor.html" %} 
{% block title %} All Patients {% endblock %} 
{% block body %}
    {% include "usermanagement/patient-profile.html" %}
{% endblock %}

usermanagement/templates/usermanagement/home.html
{% load static %}

<!DOCTYPE html>
<html>

<!-- Mirrored from thememakker.com/templates/swift/hospital/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 20 Nov 2021 08:11:15 GMT -->
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<title> Home </title>
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="{% static 'usermanagement/plugins/bootstrap/css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" type="text/css">
<link rel="stylesheet" href="{% static 'usermanagement/plugins/morrisjs/morris.css' %}"/>
<!-- Custom Css -->
<link rel="stylesheet" href="{% static 'usermanagement/css/main.css' %}"/>
</head>

<body class="theme-cyan">
<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-cyan">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

<!-- Overlay For Sidebars -->
<div class="overlay"></div>

<!-- Top Bar -->
<nav class="navbar clearHeader">
    <div class="col-12">
        <div class="navbar-header"> <a href="javascript:void(0);" class="bars"></a><a class="navbar-brand" href="{% url 'usermanagement:home' %}">Polyclinic Fultang</a> </div>
        <ul class="nav navbar-nav navbar-right">
            {% include 'usermanagement/roles.html' %}
        </ul>
    </div>
</nav>
<!-- #Top Bar -->
<section> 
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar"> 
        <!-- User Info -->
        <div class="user-info">
            {% if user.profile_pic %}
                <div class="admin-image"> <a href="{% url 'usermanagement:user-profile' user.id %}">
                    <img 
                        style="max-height: 99px;
                        max-width: 99px;
                        object-fit: contain;
                        border-radius: 50%;" src="{{user.profile_pic.url}}" alt=""> </a> </div>
            {% else %}
                <div class="admin-image"> <a href="{% url 'usermanagement:user-profile' user.id %}"> 
                    <img
                        style="max-height: 99px;
                        max-width: 99px;
                        object-fit: contain;
                        border-radius: 50%;" src="{% static 'usermanagement/images/default-pp.jpeg' %}" alt=""> </a> </div>
            {% endif %}
            <div class="admin-action-info"> <span>Welcome</span>
                <h3>{{ user.username|capfirst }}</h3>
                <ul>
                    <li><span style="color:white"> Sign Out </span></li>
                    <li><a href="{% url 'account_logout' %}" title="sign out" ><i class="zmdi zmdi-sign-in"></i></a></li>
                </ul>
            </div>
            <div class="quick-stats">
                <h5> Please Select a Role </h5>
                <h5> From the Work As Menu </h5>
                {% comment %} <ul>
                    <li><span>16<i>Patient</i></span></li>
                    <li><span>20<i>Panding</i></span></li>
                    <li><span>04<i>Visit</i></span></li>
                </ul> {% endcomment %}
            </div>
        </div>
        <!-- #User Info --> 
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">MAIN NAVIGATION</li>
                <li class="active open"><a href="{% url 'usermanagement:home' %}"><i class="zmdi zmdi-home"></i><span>Home</span></a></li>                                               
                
                <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-account-o"></i><span>Departments</span> </a>
                    <ul class="ml-menu">
                        {% for department in departments %}
                        <li><a href="#">{{department.get_name_display}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
        <!-- #Menu -->
    </aside>
</section>

<section class="content home">
    <div class="container-fluid">
        {% if messages %}
            <div>
                <ul>
                {% for message in messages %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        <strong>{{message}}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
        <small class="text-muted">Welcome to Polyclinic Fultang</small>
        <h1> Home page </h1>
        <p> brief introduction about polyclinic Fultang </p>
    </div>

    <div class="row clearfix">
        {% for department in departments %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card">
                <a href="#"><img style="height:168px;" class="card-img-top" src="{{department.icon.url}}" alt="Card image"></a>
                <div class="card-body">
                    <h4 class="card-title">{{department.get_name_display}}</h4>
                    <p class="card-text">{{department.description}}</p>
                    {% comment %} <a href="#" class="btn btn-raised g-bg-cyan waves-effect waves-effect">Deparment Info</a> {% endcomment %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section> 

<div class="color-bg-custom"></div>



<!-- Jquery Core Js --> 
<script src="{% static 'usermanagement/bundles/libscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js --> 
<script src="{% static 'usermanagement/bundles/vendorscripts.bundle.js' %}"></script> <!-- Lib Scripts Plugin Js --> 

<script src="{% static 'usermanagement/bundles/chartscripts.bundle.js' %}"></script> <!-- Chart Plugins Js -->
<script src="{% static 'usermanagement/bundles/sparklinescripts.bundle.js' %}"></script> <!-- Chart Plugins Js -->

<script src="{% static 'usermanagement/bundles/mainscripts.bundle.js' %}"></script><!-- Custom Js -->
<script src="{% static 'usermanagement/js/pages/index.js' %}"></script>
<script src="{% static 'usermanagement/js/pages/charts/sparkline.min.js' %}"></script>
</body>

<!-- Mirrored from thememakker.com/templates/swift/hospital/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 20 Nov 2021 08:11:50 GMT -->
</html>

usermanagement/templates/usermanagement/modify-payment.html
{% extends "usermanagement/base_reception.html" %} 
{% block title %} Reception {% endblock %} 
{% block body %}

{% endblock %}